### ISSUE TITLE
NameError: name '_supported_compress_extensions' is not defined

### ISSUE THREAD

**Issue by abjoschevaro** [glozanoa/hpc#1]
Problema encontrado en método uncompress() de la clase Package
Parámetros del objeto:
john = Package("john", pkgver="1.9.0", pkgrel=1, pkgdesc="Password Cracker"
, basedir="/home/abjos/Development/", source="https://github.com/openwall/john/archive/1.9.0-Jumbo-1.tar.gz")                                         

----> 1 john.download()

~/Development/debug_HPC/untitled.py in download(self)
    153             self.compress_source = os.path.join(os.getcwd(), compress_file)
    154 
--> 155             self.pkgdir = self.uncompress()
    156 
    157     #tested

~/Development/debug_HPC/untitled.py in uncompress(self)
    169         if _endswith(compress_file,suffixs=["tar", "tar.bz2", "tar.gz", "tar.xz"]):
    170             uncompress_cmd = f"tar -xvf {self.compress_source}"
--> 171             uncompress_directory = _del_suffix(compress_file)
    172 
    173         elif _endswith(compress_file,suffixs="bz2"):

~/Development/debug_HPC/untitled.py in _del_suffix(compress_file, suffix)
    223                                              "tar.xz", "gz", "bz2", "zip", "xz")
    224 
--> 225             for suffix_compress in _supported_compress_extensions:
    226                 if compress_file.endswith(suffix_compress):
    227                     return compress_file[:-len(suffix_compress)-1]

**Comment by glozanoa** [comment]
The problem was a typo, the variable `_supported_compress_extensions` will be `supported_compress_extensions`.
I have updaded the code, so you only have to make a pull from the master branch.
